ImbuzzitApiBundle_user:
        resource: "@ImbuzzitApiBundle/Resources/config/routing/user.yml"
        prefix:   /

ImbuzzitApiBundle_stream:
        resource: "@ImbuzzitApiBundle/Resources/config/routing/stream.yml"
        prefix:   /stream