parameters:
#    imbuzzit_api.example.class: Imbuzzit\ApiBundle\Example

services:
#    imbuzzit_api.example:
#        class: %imbuzzit_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
