security:
    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm:   sha1
          iterations: 1
          encode_as_base64: false
        Imbuzzit\ApiBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern:  ^/login$
            anonymous: true

        admin:
            pattern:   ^/admin
            anonymous: true
            provider:  in_memory
            form_login:
                login_path: ImbuzzitAdminBundle_login
                check_path: ImbuzzitAdminBundle_login_check
            logout:
                path:   ImbuzzitAdminBundle_logout
                target: /

        api:
            pattern:    ^/api
            http_basic: true
            stateless:  true
            anonymous: true

    #access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
