api_user:
    pattern:  /
    defaults: { _controller: "ImbuzzitApiBundle:User:index" }

api_user_show:
    pattern:  /{id}/show
    defaults: { _controller: "ImbuzzitApiBundle:User:show" }

api_user_new:
    pattern:  /new
    defaults: { _controller: "ImbuzzitApiBundle:User:new" }

api_user_create:
    pattern:  /create
    defaults: { _controller: "ImbuzzitApiBundle:User:create" }
    requirements: { _method: post }

api_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ImbuzzitApiBundle:User:edit" }

api_user_update:
    pattern:  /{id}/update
    defaults: { _controller: "ImbuzzitApiBundle:User:update" }
    requirements: { _method: post }

api_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ImbuzzitApiBundle:User:delete" }
    requirements: { _method: post }
