<?php

namespace Imbuzzit\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamRepository extends EntityRepository
{
  public function getStreamByUserId($user_id, $limit = 10)
  {
    $qb = $this->createQueryBuilder('s')
        ->where('s.createdBy = :user_id')
        ->setParameter('user_id', $user_id)
        ->addOrderBy('s.id', "DESC")
        ->getQuery();
    
    $result = $qb->getResult();
    var_dump($result);die;
    return $result;
  }
}
