ImbuzzitAdminBundle_user:
        resource: "@ImbuzzitAdminBundle/Resources/config/routing/user.yml"
        prefix:   /user
ImbuzzitAdminBundle_login:
    pattern:   /login
    defaults:  { _controller: ImbuzzitAdminBundle:Security:login }
 
ImbuzzitAdminBundle_login_check:
    pattern:   /login_check
 
ImbuzzitAdminBundle_logout:
    pattern:   /logout